/*
 * Messages API
 *
 * API for messages
 *
 * API version: 1.0.0
 * Contact: peterstirrup96@hotmail.co.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Error The structure of this type is a subset of the fields found in the JSON:API error type specification (https://jsonapi.org/format/#errors).
type Error struct {
	Status int32                  `json:"status"`
	Title  string                 `json:"title"`
	Detail string                 `json:"detail,omitempty"`
	Meta   map[string]interface{} `json:"meta,omitempty"`
}
