/*
 * Messages API
 *
 * API for messages
 *
 * API version: 1.0.0
 * Contact: peterstirrup96@hotmail.co.uk
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// Contact struct for Contact
type Contact struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}
